<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnswerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('answers')->insert([
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "1"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "1"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "1"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "1"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "2"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "2"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "2"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "2"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "3"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "3"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "3"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "3"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "4"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "4"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "4"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "4"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "5"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "5"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "5"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "5"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "6"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "6"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "6"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "6"],
            ['answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "7"],
            ['answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "7"],
            ['answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "7"],
            ['answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "7"],


            ['answer' => "Так", 'correctness' => 0, "questions_id" => "8"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "8"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "9"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "9"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "10"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "10"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "11"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "11"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "12"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "12"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "13"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "13"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "14"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "14"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "15"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "15"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "16"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "16"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "17"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "17"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "18"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "18"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "19"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "19"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "20"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "20"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "21"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "21"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "22"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "22"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "23"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "23"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "24"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "24"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "25"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "25"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "26"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "26"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "27"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "27"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "28"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "28"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "29"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "29"],

            ['answer' => "Так", 'correctness' => 0, "questions_id" => "30"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "30"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "31"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "31"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "32"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "32"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "33"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "33"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "34"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "34"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "35"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "35"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "36"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "36"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "37"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "37"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "38"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "38"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "39"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "39"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "40"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "40"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "41"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "41"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "42"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "42"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "43"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "43"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "44"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "44"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "45"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "45"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "46"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "46"],
            ['answer' => "Так", 'correctness' => 0, "questions_id" => "47"],
            ['answer' => "Ні", 'correctness' => 1, "questions_id" => "47"],
            ['answer' => "Так", 'correctness' => 1, "questions_id" => "48"],
            ['answer' => "Ні", 'correctness' => 0, "questions_id" => "48"],
           
        ]);
    }
}
