<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnswerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('answers')->insert([
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "1"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "1"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "1"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "1"],
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "2"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "2"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "2"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "2"],
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "3"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "3"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "3"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "3"],
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "4"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "4"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "4"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "4"],
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "5"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "5"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "5"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "5"],
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "6"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "6"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "6"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "6"],            
            [ 'answer' => "Взагалі не турбували", 'correctness' => 0, "questions_id" => "7"],
            [ 'answer' => "Кілька днів", 'correctness' => 1, "questions_id" => "7"],
            [ 'answer' => "Більше половини часу", 'correctness' => 2, "questions_id" => "7"],
            [ 'answer' => "Майже кожен день", 'correctness' => 3, "questions_id" => "7"],

          
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "8"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "8"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "8"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "8"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "8"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "9"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "9"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "9"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "9"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "9"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "10"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "10"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "10"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "10"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "10"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "11"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "11"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "11"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "11"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "11"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "12"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "12"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "12"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "12"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "12"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "13"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "13"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "13"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "13"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "13"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "14"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "14"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "14"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "14"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "14"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "15"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "15"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "15"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "15"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "15"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "16"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "16"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "16"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "16"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "16"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "17"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "17"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "17"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "17"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "17"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "18"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "18"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "18"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "18"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "18"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "19"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "19"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "19"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "19"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "19"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "20"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "20"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "20"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "20"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "20"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "21"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "21"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "21"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "21"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "21"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "22"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "22"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "22"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "22"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "22"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "23"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "23"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "23"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "23"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "23"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "24"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "24"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "24"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "24"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "24"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "25"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "25"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "25"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "25"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "25"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "26"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "26"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "26"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "26"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "26"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "27"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "27"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "27"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "27"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "27"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "28"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "28"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "28"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "28"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "28"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "29"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "29"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "29"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "29"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "29"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "30"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "30"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "30"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "30"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "30"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "31"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "31"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "31"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "31"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "31"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "32"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "32"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "32"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "32"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "32"],
            [ 'answer' => "Абсолютно не згоден", 'correctness' => 0, "questions_id" => "33"],
            [ 'answer' => "Скоріше не згоден", 'correctness' => 1, "questions_id" => "33"],            
            [ 'answer' => "Ні те ні інше", 'correctness' => 2, "questions_id" => "33"],
            [ 'answer' => "швидше згоден", 'correctness' => 3, "questions_id" => "33"],
            [ 'answer' => "абсолютно згоден", 'correctness' => 4, "questions_id" => "33"],
           
            ]);
    }
}
